title: Community Legal Clinic Manual, Law Society of Singapore
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
exclude: ["*.tmp","*.sh"]
section_order:
  - Community Legal Clinic Manual
  - Clinic Management
  - Civil Claims (General)
  - Family Law
  - Bankruptcy and Insolvency
  - Criminal Law and Procedure
  - Property
  - Intellectual Property
  - Wills, Intestacy, Probate and Administration
  - Data Protection Law
  - Advance Medical Directive
  - Juvenile Issues
  - Military Law
  - Alternative Dispute Resolution
  - The Traffic Court
bonsai_url: https://first-cluster-5446942761.ap-southeast-2.bonsaisearch.net/probono/md/_search?pretty
bonsai_credential: 4et5fzvqdw:5as4dekv3t
