title: Community Legal Clinic Manual, Law Society of Singapore
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
exclude: ['*.tmp','*.sh','pre-push']
section_order:
  - Community Legal Clinic Manual
  - Clinic Management
  - Civil Claims (General)
  - Family Law
  - Bankruptcy and Insolvency
  - Criminal Law and Procedure
  - Property
  - Intellectual Property
  - Wills, Intestacy, Probate and Administration
  - Data Protection Law
  - Advance Medical Directive
  - Juvenile Issues
  - Military Law
  - Alternative Dispute Resolution
  - The Traffic Court
environment: LOCAL
search_endpoint_LOCAL: http://127.0.0.1:3000/search
search_endpoint_DEV: https://community-legal-manual.herokuapp.com/search

