source "https://rubygems.org"
gem 'rack-jekyll'
gem 'rake'
gem 'jekyll' ,'>=3.5.2'
gem 'jekyll-sass-converter' ,'>=1.5.0'
gem 'kramdown' ,'>=1.13.2'
gem 'liquid' ,'>=4.0.0'
gem 'rouge' ,'>=1.11.1'
gem 'minima' ,'>=2.1.1'
gem 'jekyll-feed' ,'>=0.9.2'
gem 'jekyll-gist' ,'>=1.4.1'
gem 'jekyll-paginate' ,'>=1.1.0'
gem 'jekyll-coffeescript' ,'>=1.0.2'
gem 'jekyll-seo-tag' ,'>=2.3.0'
gem 'jekyll-avatar' ,'>=0.5.0'
gem 'jekyll-relative-links' ,'>=0.5.0'
gem 'jekyll-optional-front-matter', '>=0.2.0'
gem 'jekyll-readme-index' ,'>=0.1.0'
gem 'jekyll-default-layout' ,'>=0.1.4'
gem 'jekyll-titles-from-headings' ,'>=0.4.0'
gem 'listen' ,'>=3.0.6'
gem 'activesupport' ,'>=4.2.9'
